### ISSUE TITLE
Initial Build throws errors

### ISSUE THREAD

**Issue by mkaul** [pwa-builder/pwa-starter#10]
Fresh install yields **error-this-is-undefined**

git clone https://github.com/pwa-builder/pwa-starter.git

pwa-starter$ npm i && npm run build

> pwa-starter@0.0.1 build pwa-starter
> rimraf dist/ && tsc && rollup -c

index.html → dist...

The service worker file was written to dist/pwabuilder-sw.js
The service worker will precache 16 URLs, totaling 281 kB.

(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#**error-this-is-undefined**
build/pages/app-index.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
...and 1 other occurrence
build/pages/app-about.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
...and 1 other occurrence
build/pages/app-home.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
...and 1 other occurrence
build/components/header.js
1: var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
                     ^
2:     var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
3:     if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
...and 1 other occurrence
created dist in 2.4s

**Comment by ohioh** [comment]
I have an error on build too with following message:

> pwa-starter@0.0.1 build /Users/ohiohohioh/Documents/APP/pwa/pwa-starter
> rimraf dist/ && tsc && rollup -c

[!] Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/@babel/preset-env/lib/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/lib/bundle.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/lib/write-sw-using-default-template.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/generate-sw.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup-plugin-workbox/dist/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/rollup.config.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup/dist/bin/rollup
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/@babel/preset-env/lib/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/lib/bundle.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/lib/write-sw-using-default-template.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/generate-sw.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/workbox-build/build/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup-plugin-workbox/dist/index.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/rollup.config.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .js] (/Users/ohiohohioh/Documents/APP/pwa/pwa-starter/node_modules/rollup/dist/shared/loadConfigFile.js:547:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-starter@0.0.1 build: `rimraf dist/ && tsc && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwa-starter@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ohiohohioh/.npm/_logs/2020-09-02T19_05_11_715Z-debug.log

**Comment by jgw96** [comment]
@mkaul That is actually a warning, not error, from Rollup, as described here https://rollupjs.org/guide/en/#error-this-is-undefined. We will look into getting rid of this warning in the next release (: @ohioh , let me see if i can repro your issue.

**Comment by jgw96** [comment]
@ohioh , unfortunately I am not able to reproduce the error you are running into, would you mind opening a new issue with more info? Thanks!
