### ISSUE TITLE
Android aab-package error on Google Play Store

### ISSUE THREAD

**Issue by MarkKnochen** [pwa-builder/pwa-starter#22]
Hello,

in Google Play Store i got a error in the tests:

java.lang.RuntimeException: Unable to start activity ComponentInfo{.....twa.LauncherActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

What can I do, to publish the PWA in the PlayStore?

Thank You

**Comment by jgw96** [comment]
Hello! As this issue is unrelated to this repository I am going to close this issue for now. Thanks!
