### ISSUE TITLE
I need example for  to undertsand scope, please

### ISSUE THREAD

**Issue by psilvao** [pwa-builder/pwa-starter#7]
Hi, i was learning your software for to build PWA, first of all i was watching my manifest, what means scope??

{
	"name" : "Progressive Web App ejemplo",
	"short_name" : "pwa-geo",
	"description" : "Ubicacion del punto en un mapa",
	"icons" : [
		{
			"src": "https://pwa.anantara.cl/images/spash-screen-image-512x512-pwa.png",
			"sizes": "512x512"
		}],
	"start_url" : "https://pwa.anantara.cl/",
	"display" : "fullscreen",
	"theme_color" : "#764ABC",
	"background_color" : "#764ABC",
	"url" : "https://pwa.anantara.cl",
	"lang" : "Spanish",
	"screenshots" : [],
	"orientation" : "portrait-primary",
	"generated" : ""
}

**Comment by jgw96** [comment]
Hey! This article should be able to help you out https://developer.mozilla.org/en-US/docs/Web/Manifest/scope. Thanks for giving the starter a try!
